# Diseño de experimentos {#doe}

El diseño de experimentos fue inventado por Ronald A. Fisher en las décadas de 1920 y 1930 en la Estación Experimental de Rothamsted, conocida ahora como Rothamsted Research. En el primer libro de Fisher sobre diseño de experimentos mostró cómo se podían extraer conclusiones válidas a partir de experimentos con fluctuaciones naturales como la temperatura, las condiciones del suelo y la lluvia, es decir, en presencia de variables molestas o perturbadoras. 

Las variables perturbadoras conocidas suelen causar sesgos sistemáticos en grupos de resultados (por ejemplo, variación entre lotes). Las variables perturbadoras desconocidas suelen causar variabilidad aleatoria en los resultados y se denominan variabilidad inherente o ruido. Aunque el método de diseño experimental se utilizó por primera vez en un contexto agrícola, el método se ha aplicado con éxito en otras industrias y ámbitos. 

En la @sec-tipest se presentaron los tipos de estudio, en esta sección se presentan los principios básicos y los principales diseños experimentales usados en agricultura. ¿Por qué es importante el diseño experimental? Supongamos que deseamos comparar dos variedades de maíz, una variedad estándar ya conocida a la que llamaremos V1 y una variadad nueva de la que recién hemos escuchado a la que llamaremos V2. Podríamos plantar la mitad de un campo con V1 y la otra mitad con V2. Se plantan las dos variedades exactamente el mismo día y se gestionan las dos mitades del campo exactamente igual durante todo el período vegetativo. A lo largo de la cosecha, se llevan registros separados del rendimiento de cada mitad del campo, de modo que al final de la temporada se obtiene el rendimiento total de cada variedad. Supongamos que, en este caso, la nueva variedad (V2) tiene un rendimiento un 20% mayor que la variedad estándar (V1). ¿Puede asegurar que la nueva variedad es mejor que la  variedad estándar? La respuesta es no, porque puede haber otros factores que hayan provocado la diferencia de rendimiento, como por ejemplo:

- V2 se plantó en una parte del campo que tenía mejor suelo.
- Un extremo del campo era más húmedo que el otro y algunos de las plantes se infectaron con oídio.
- Las diferencias de textura del suelo provocaron un aumento de la humedad del suelo de un extremo del campo al otro.
- Una parte del campo con la variedad estándar recibe sombra por la tarde de una línea de árboles adyacente.
- La presencia de malezas es mayor en una parte del campo con V1. 
- Los bosques o zonas silvestres adyacentes son una fuente de plagas que afectan más a un extremo del campo que al otro.

Como el experimento no se preparó para tener en cuenta la variabilidad del campo, no se puede concluir si el rendimiento superior de una variedad se debió a la propia variedad o a diferencias en las condiciones de cultivo. No se repitieron los tratamientos. Por lo tanto, no tiene forma de aplicar una prueba estadística a sus datos. Si piensa en su propia explotación, ¿qué otras fuentes de variación podrían influir en su pregunta de investigación?

Con el diseño experimental y el análisis estadístico adecuados, puede identificar y aislar los efectos de la variación natural y determinar si las diferencias entre tratamientos son «reales», dentro de ciertos niveles de probabilidad. La elección del diseño experimental, dependerá en gran medida de la pregunta de investigación que se plantee y del número de tratamientos del experimento.

## Conceptos básicos


1. **Unidad experimental**: el objeto o espacio al cual se aplica el tratamiento y donde se analiza la variable o variables investigadas. Dependiendo del tipo de experimento la unidad experimental puede ser un animal, un árbol o una parcela. Cuando la unidad experimental es una parcela, en algunas ocsiones se presenta el efecto borde.

::: {.callout-note}
## Efecto borde
Las diferencias que se observan en el crecimiento y producción de plantas que se ubican en los perímetros de una parcela comparadas con las que se ubican en la zona central de la parcela se conocen como efecto borde, este efecto puede ser causado por: 

- Vecindad de las parcelas o áreas no cultivadas lo que puede producir que las plantas del perímetro tengan menor competencia de luz y nutrientes.
- Competencia entre los tratamientos.
:::

2. **Tratamiento**: el tratamiento es el procedimiento cuyo efecto se mide y que se desea comparar con otros tratamientos. Ejemplos de tratamiento pueden ser la ración alimenticia, una variedad de semillas, un programa de riego, la concentración de un herbicida o fungicida, una combinación de temperatura y humedad. 

3. **Unidad de muestreo**: el efecto del tratamiento se puede medir en una fracción de la unidad experimental o en toda la unidad experimental. Es decir que la unidad de muestreo puede ser toda la unidad experimental o una fracción de la misma. Ejemplos de unidad de muestreo son: un animal sometido a una ración de alimento, muestra aleatoria de las hojas de una planta, la cosecha de 10 plantas de la unidad experimental en una parcela.

4. **Error experimental**: Medida de la variación existente entre las observaciones realizadas en las unidades experimentales tratadas en forma similar. La variación puede provenir de dos fuentes:

::: {.callout-tip}
## Fuentes de la variación
- Variabilidad propia del material experimental al que se aplican los tratamientos. 
- Variación resultado de cualquier falta de uniformidad en la realización física del experimento.
:::

5. **Repeticiones**: número de veces que un tratamiento aparece en un experimento.

::: {.callout-tip}
## Funciones de las repeticiones
- Permitir una estimación del error experimental.
- Mejorar la precisión de un experimento mediante la reducción del error estándar de una media de tratamiento.
- Aumentar el alcance de la inferencia del experimento mediante la selección y el uso adecuado de unidades experimentales más variables.
- Controlar la varianza del error. 
:::

Aumentar el número de repeticiones, la mayoría de las veces, mejora la precisión. La elección del número de repeticiones de un experimento depende de varios factores, como el nivel de confianza deseado, la variabilidad esperada de los datos, el tamaño del efecto que se desea detectar, la disponibilidad de recursos y la complejidad del experimento; por lo general, un buen punto de partida es intentar realizar al menos tres repeticiones por condición, pero es posible que se necesiten más dependiendo de la pregunta de investigación específica y del diseño experimental.

## Principios básicos

En el diseño de experimentos, el __control del error experimental__ se refiere a la minimización de la variabilidad de los resultados que no está directamente relacionada con los factores estudiados, lo que se consigue mediante los principios como la aleatorización, la replicación y el bloqueo (control local), cuyo objetivo es aislar el verdadero efecto de las variables manipuladas y reducir la influencia de factores ajenos al resultado. 

1. **Aleatorización**: La asignación aleatoria de los tratamientos a las unidades experimentales ayuda a distribuir por igual cualquier fuente desconocida de variación entre los grupos de tratamiento, reduciendo el sesgo. 
2. **Repetición**: La repetición de cada condición de tratamiento varias veces en diferentes unidades experimentales permite estimar el error experimental y aumenta la precisión de los resultados. 
3. **Bloqueo (control local)**: Agrupar unidades experimentales similares en bloques y asignar tratamientos dentro de cada bloque ayuda a controlar las fuentes conocidas de variación que podrían afectar a los resultados, como las diferencias en las condiciones ambientales. 

## Análisis de Varianza (ANOVA, ANDEVA)

El **An**álisis **De** **Va**rianza o prueba ANOVA (abreviatura de **An**alysis **o**f **Va**riance) es una técnica que se utiliza para comparar las medias de más de dos grupos. Las comparaciones se hacen analizando la  **variabilidad** dentro y entre los grupos. Como toda prueba de hipótesis tiene una hipótesis nula ($H_0$), en este caso, para los $k$ grupos o poblaciones la hipótesis nula es que las medias de todos los grupos o poblaciones son iguales; mientras que la hipótesis alternativa es que al menos una de las medias es diferente:

$$
\begin{cases}
H_0: \mu_1 = \mu_2 = \ldots = \mu_k \\
H_1: \exists \; i, \; j \; \text{tal que} \; \mu_i \neq \mu_j
\end{cases}
$$

### Modelos para el análisis de varianza

Vamos a suponer que deseamos comparar $k$ tratamientos o niveles para un $único factor$, cada tratamiento o nivel tiene $r$ repeticiones. La respuesta observada es una variable aleatoria. Los datos del modelo se pueden presentar de la siguiente forma:



| Trat.-Nivel | Repetición 1	| Repetición 2| $\ldots$ 	| Repetición $r$ |
|------------:|--------------:|------------:|----------:|---------------:|
| 1           | $y_{11}$     	| $y_{12}$ 	  | $\ldots$ 	| $y_{1r}$ 	     |
| 2           | $y_{21}$     	| $y_{22}$ 	  | $\ldots$ 	| $y_{2r}$ 	     |
| $\vdots$    | $\vdots$     	| $\vdots$ 	  | $\ldots$ 	| $\vdots$ 	     |
| $k$         | $y_{k1}$     	| $y_{k2}$ 	  | $\ldots$ 	| $y_{kr}$ 	     |

: Datos de un experimento de un factor único {#tbl-datosanova}

El modelo matemático correspondiente puede ser escrito como:

$$
y_{ij} = \mu_i + \epsilon_{ij} \quad \forall \; i,j
$$ {#eq-modmed}

donde $y_{ij}$ corresponde a la $j-ésima$ repetición para el $i-ésimo$ nivel o tratamiento, $\mu_i$ es la media del $i-ésimo$ nivel o tratamiento y $\epsilon_{ij}$ es un componente de error aleatorio que incorpora las otras fuentes de variabilidad en el experimento. Se supone además que los errores tienen media 0. La @eq-modmed recibe el nombre de **modelo de medias**.

Si definimos $\mu_i=\mu+\alpha_i$, la @eq-modmed queda escrita de la forma:

$$
y_{ij} = \mu + \alpha_i +  \epsilon_{ij} \quad \forall \; i,j
$$ {#eq-modeff}

En la @eq-modeff llamada comúnmente el **modelo de efectos**, el término $\mu$ es un parámetro para todos los tratamientos y se conoce como la **media general** y $\alpha_i$ es el efecto del tratamiento (nivel) $i$. 

::: {.callout-important}
## ¿Efectos fijos o aleatorios?
La @eq-modeff tiene dos posibilidades.
 
- Los $k$ tratamientos fueron escogidos por el experimentador.
- Los $k$ tratamientos fueron tomados de una muestra aleatoria de muchos tratamientos.

En el primer caso, se puede probar la hipótesis sobre las medias de los tratamientos, y las conclusiones solo aplicarán a los niveles o tratamientos escogidos en el análisis.  No se puede extender las conclusiones a tratamientos parecidos. Además es posible calcular los parámetros $\mu$, $\alpha_i$ y $\sigma^2$. Este modelo se llama **modelo de efectos fijos**.

En el segundo caso las conclusiones que se basan en la muestra de tratamientos, se pueden extender a todos los tratamientos. En este caso los $\alpha_i$ son variables aleatorias. Por lo que conocer sus valores exactos no es necesariamente importante. Por otro lado, se pueden verificar hipótesis sobre la variabilidad de $\alpha_i$ y estimar el valor de esta variabilidad. Este modelo se llama **modelo de efectos aleatorios** o **modelo de componentes de la varianza**.
:::

### Tabla ANOVA

Sea $\bar{y}$ la media general, o media de todos los  datos, y $\bar{y_i}$ la media por el grupo $i-ésimo$. La suma cuadrática total está dada por

$$
SCT = \sum_i{\sum_j{(y_{ij}-\bar{y})}^2}
$$ {#eq-SCT}

Esto mide la variación con respecto al centro de todos los datos. Un análisis de varianza divide $SCT$ en dos términos:

$$
SCT = \sum_i{\sum_j{(y_{ij}-\bar{y}_i)}^2} + \sum_i{n_i\left(\bar{y}_i-\bar{y}\right)^2}
$$ {#eq-SCT2}

El primer término es la suma de los cuadrados del error (SCE). La suma  $\sum_j{(y_{ij}-\bar{y}_I)}^2$, mide la variación dentro del i-ésimo grupo. La suma de los cuadrados del error es entonces una medida de la variabilidad dentro de los grupos. El segundo término en la @eq-SCT2 es llamada la suma cuadrática de los tratamientos (SCTr). La SCTr compara la media para cada grupo, $\bar{y}_i$, con la media general. Esta mide la variabilidad entre las medias de las muestras. La @eq-SCT2 se puede reescribir como

$$
SCT = SCE + SCTr
$$ {#eq-sct3}

Si los datos provienen de una media común, esperaríamos que SCE y SCT sean aproximadamente iguales. Por otro lado si SCE y SCT son muy distintas, tendríamos evidencia contra la hipótesis nula. ¿Cómo podríamos decir si las diferencias se deben a que la hipótesis nula es falsa o unicámente a la variación muestral? El estadístico usado en este caso es:

$$ 
F = \dfrac{\frac{SCTr}{k-1}}{\frac{SCE}{n-k}}
$$ {#eq-fstat} 

Para obtener una escala adecuada, cada término se divide por sus respectivos grados de libertad, obteniendo la suma media de los cuadrado de los tratamientos o los errores (MCTr o MCE).
$$
MCTr=\frac{SCTr}{k-1}
$$

$$
MCE = \frac{SCE}{n-k}
$$
Los grados de libertad para SCT son $n-1$, para $SCE$ los grados de libertad son $n-k$. Usando @eq-sct3 para los grados de libertad: $gl(Total)=gl(Error)+gl(Tratamiento)$ y reemplazando los grados de libertad totales y del error se obtiene que los grados de libertad de los tratamientos son $k-1$. El procedimiento de la prueba se resume en la **Tabla ANOVA** que se muestra en la  @tbl-anova

| Fuente de Variación                	| Grados de Libertad 	| Suma de Cuadrados 	| Media Cuadrática 	| $F$ 	|
|------------------------------------	|--------------------	|-------------------	|------------------	|---	|
| Entre tratamientos                 	| $k-1$              	| $SCTr = \sum_i{n_i\left(\bar{y}_i-\bar{y}\right)^2}$                  	| $MCTr=\frac{SCTr}{k-1}$                 	| $F=\frac{MCTr}{MCE}$  	|
| Error (dentro de los tratamientos) 	| $n-k$               | $SCE = \sum_i{\sum_j{(y_{ij}-\bar{y}_i)}^2}$                  	| $MCE = \frac{SCE}{n-k}$                 	|   	|
| Total                              	| $n-1$               | $SCT = \sum_i{\sum_j{(y_{ij}-\bar{y})}^2}$                  	|                  	|   	|

: Tabla del Análisis de Varianza para el modelo de un único factor {#tbl-anova}


## Diseño completo al azar

El diseño experimental más sencillo es un diseño completamente al azar. Este funciona mejor en situaciones muy controladas y condiciones muy uniformes. Por este motivo, el diseño completamente al azar no se suele utilizar en experimentos de campo. Puede utilizarlo si trabaja en un campo muy uniforme, en un invernadero o en una cámara de crecimiento, o si no tiene ni idea de las condiciones de cultivo. de crecimiento, o si no tiene ni idea de la variabilidad de su campo.

El modelo matemático para los datos provenientes de un diseño completo al azar, con un número diferente de repeticiones para cada nivel del factor puede ser escrito como;

$$
y_{ij} = \mu +\alpha_i + \epsilon_{ij}
$$

## Diseño de bloques completos al azar



## Diseño de cuadro latino

## Pruebas de comparaciones múltiples paramétricas

## Pruebas no paramétricas equivalentes al análisis de varianza

## Pruebas de comparaciones múltiples no paramétricas

## Diseño factorial

## Ejercicios {.unnumbered} 

::: {#exr-doe1}
Con los datos y el proyecto del @exr-seis. Resuelva las siguientes cuestiones. 
::: 
a. ¿Existen diferencias significativas para la altura por variedad en la primera medición?
b. ¿Existen diferencias significativas para la altura por variedad en la segunda medición?
c. ¿Existen diferencias significativas para el diámetro por variedad en la tercera medición?
d. ¿Existen diferencias significativas para el diámetro por variedad en la cosecha?
e. Crear un conjunto llamado _basetotal_ que contenga los datos previos a la cosecha y de la cosecha. Para lograr esto siga los siguientes pasos.


- Cree el conjunto _datosmaiz2_ a partir de _datosmaiz_, en este conjunto debe renombrar las variables _Medicion_ y _Diametro_ como _Medición_ y _Diámetro_ respectivamente. Además debe crear la variable _DDS_ que sea 15 cuando _Medición_ sea igual a 1, 30 cuando _Medición_ sea igual a 2 y 45 cuando _Medición_ sea igual a 2. Por último remueva la variable _Fecha_. 
- Cree el conjunto _cosecha2_ a partir de _cosecha_. En este conjunto cree la variable _Medición_ que tomará el valor de 4 y la variable _DDS_ que tomará el valor de 91.
- Finalmente una _datosmaiz2_ y _cosecha2_ para crear el conjunto _basetotal_.

f. Verifique la existencia de diferencias significativas en las alturas por variedad. Realice esta verificación para todas las mediciones y guarde los resultados en la tabla _valorespalt_.
g. Verifique la existencia de diferencias significativas en los diámetros por variedad. Realice esta verificación para todas las mediciones y guarde los resultados en la tabla _valorespdiam_.
h. Guarde las tablas _valorespalt_ y _valorespdiam_ en un libro llamado *anova_alt_diam.xlsx*. Las hojas de este libro se deben llamar _altura_ y _diametro_ respectivamente.

::: {#exr-doe2}
Con los datos y el proyecto del @exr-quin3, resolver las siguientes cuestiones. 
:::
a. Crear un archivo llamado _reporte_GAGS.qmd_
b. Cargar los paquetes _agricolae_, _tidyverse_, _writexl_, _readxl_ y _jtools_. 
c. Cargar los datos almacenados en el archivo de Excel, los datos deben ser almacenados en una variable llamada _data23035_. 
d. Crear una variable llamada __Diámetro__. Esta variable es el promedio del diámetro horizontal y el diámetro vertical.
e. Seleccione los datos hasta la semana 8.
f. Para evitar el efecto borde, Gabriela solamentes incluyó en su análisis las plantas 6, 7, 10 y 11. Seleccione estas plantas para realizar el análisis.  **Nota: Para realizar las dos últimas tareas debe usar la función *filter* y combinarlas con un operador lógico adecuado.**
g. Con un título de nivel 2, crear una sección dentro del reporte llamada **_Análisis de la variable Altura_**
h. Con un título de nivel 3, crear una sección dentro del reporte llamada **_Análisis descriptivo_**
i. Crear una tabla llamada _stats_alt_ que resuma la altura por semana y por tratamiento:

  - La media y la desviación de la altura.
  - El valor crítico de la distribución $t$  para el número de observaciones calculado con un $95\%$ de confianza.
  - El error estándar de la media de la  altura.
  - Los extremos del intervalo del $95\%$ de confianza  para la media de la altura.
  - Esta tabla no debe ser mostrada en el reporte.

j. Con ayuda de la tabla _stats_alt_ crear un gráfico de evolución de la altura a lo largo de las semanas, incluya barras de error con los extremos del intervalo de confianza. Separe las líneas por tratamiento. En la carpeta gráficos guardar el gráfico generado con el nombre _evol_alt.png_. Interpretar el gráfico generado.
k. Con un título de nivel 3, crear una sección dentro del reporte llamada **_Análisis inferencial_**.
l. En la primera semana ¿existen diferencias significativas en la altura promedio por tratamiento? Para contestar esta pregunta muestre el resultado de la prueba ANOVA.
m. En las 8 semanas ¿existen diferencias significativas en la altura promedio por tratamiento? Para contestar esta pregunta muestre los valores $p$ de las pruebas ANOVA. Se recomienda trabajar con el siguiente flujo de trabajo:

  - Realizar la prueba ANOVA por semana para la comparación de la altura promedio por tratamiento, en una tabla llamada _valsp_aov_alt_ guardar los valores $p$ de cada prueba ANOVA.
  - Modificar la tabla _stats_alt_ para que quede como se muestra en la @tbl-doe2, el resultado guardarlo en una variable llamada _stats_alt2_:

| Semana | T1                            | T2                            | T3                            |
|----------------------------|-------------------------------|-------------------------------|-------------------------------|
| 1                          | $\bar{x}_{T1-1} \pm s_{T1-1}$ | $\bar{x}_{T2-1} \pm s_{T2-1}$ | $\bar{x}_{T3-1} \pm s_{T3-1}$ |
| 2                          | $\bar{x}_{T1-2} \pm s_{T1-2}$ | $\bar{x}_{T2-2} \pm s_{T2-2}$ | $\bar{x}_{T3-2} \pm s_{T3-2}$ |
| 3                          | $\dots$                       | $\dots$                       | $\dots$                       |
| 4                          | $\dots$                       | $\dots$                       | $\dots$                       |
| 5                          | $\dots$                       | $\dots$                       | $\dots$                       |
| 6                          | $\dots$                       | $\dots$                       | $\dots$                       |
| 7                          | $\dots$                       | $\dots$                       | $\dots$                       |
| 8                          | $\bar{x}_{T1-8} \pm s_{T1-8}$ | $\bar{x}_{T2-8} \pm s_{T2-8}$ | $\bar{x}_{T3-8} \pm s_{T3-8}$ |

: Tabla modelo 1. {#tbl-doe2}

  - Utilizar la función _left_join()_ para unir las tablas _stats_alt2_ y _valsp_aov_alt_, el resultado guardarlo en una tabla llamada _stats_alt3_, un ejemplo de la tabla se muestra en la @tbl-doe2_1 .En el reporte se debe incluir esta última tabla.
  
| Semana | T1                            | T2                            | T3                           | Valor $p$ |
|----------------------------|-------------------------------|-------------------------------|------------------------------|-----------|
| 1                          | $\bar{x}_{T1-1} \pm s_{T1-1}$ | $\bar{x}_{T2-1} \pm s_{T2-1}$ | $\bar{x}_{T3-1}\pm s_{T3-1}$ | $pval_1$  |
| 2                          | $\bar{x}_{T1-2} \pm s_{T1-2}$ | $\bar{x}_{T2-2}\pm s_{T2-2}$  | $\bar{x}_{T3-2}\pm s_{T3-2}$ | $pval_2$  |
| 3                          | $\dots$                       | $\dots$                       | $\dots$                      | $\dots$   |
| 4                          | $\dots$                       | $\dots$                       | $\dots$                      | $\dots$   |
| 5                          | $\dots$                       | $\dots$                       | $\dots$                      | $\dots$   |
| 6                          | $\dots$                       | $\dots$                       | $\dots$                      | $\dots$   |
| 7                          | $\dots$                       | $\dots$                       | $\dots$                      | $\dots$   |
| 8                          | $\bar{x}_{T1-8}\pm s_{T1-8}$  | $\bar{x}_{T2-8}\pm s_{T2-8}$  | $\bar{x}_{T3-8}\pm s_{T3-8}$ | $pval_8$  |

: Tabla modelo 2. {#tbl-doe2_1}

n. Guardar esta la tabla en la carpeta _resultados_ en un archivo llamado _altura.xlsx_.
o. Escribir las conclusiones de esta última tabla. 

::: {#exr-doe3}
Con los datos y el proyecto del @exr-doe1, resuelva las siguientes cuestiones.
:::

a. Usando las pruebas de Fisher, Tukey, Bonferroni y Scheffé determine dónde se encuentran las diferencias de las alturas en la primera medición.
b. Usando las pruebas de Fisher, Tukey, Bonferroni y Scheffé determine dónde se encuentran las diferencias de las alturas en la segunda medición.
c. Cree un objeto llamado _grpsaltm2_ que contenga las columnas _Variedad_, _Medición_ y _Grupos_. Para esto siga los siguientes pasos:

  - Guarde el resultado de la prueba de Fisher para la segunda medición de la altura en un objeto llamado _compaltm2_.
  - Extraiga los grupos de la comparación hecha en el paso anterior y almacenelos en la variable _grpsaltm2_.
  - Modifique el objeto _grpsaltm2_, para esto cambie los nombres de fila a una variable con el nombre _Variedad_, luego cree una columna llamada _Medición_ que tenga el número 2, remueva la columna de la Altura y finalmente renombre la columna _groups_ con el nombre _Grupos_.
d. Usando la prueba de Fisher realice las comparaciones múltiples de las medias de las alturas por variedad para cada medición.
e. Para la medición 2, grafique un diagrama de caja de la altura por medición. En este gráfico muestre además los grupos de la prueba de Fisher en la parte superior de las cajas.
f. Para todas las mediciones, grafique un diagrama de caja de la altura por medición. En cada gráfico muestre además los grupos de la prueba de Fisher en la parte superior de las cajas. Guarde cada uno de los gráficos con los nombres _boxaltM1.png_, _boxaltM2.png_, _boxaltM3.png_ y _boxaltM4.png_ respectivamente para cada medición.

::: {#exr-doe4}
Con los datos y el proyecto del ejercicio @exr-doe2 resolver las siguientes cuestiones.
:::

a. Para la semana 1, utilizando la prueba de Fisher ¿dónde se encuentran las diferencias significativas?
b. Para la semana 1, utilizando la prueba de Tukey ¿dónde se encuentran las diferencias significativas?
c. Para la semana 1, utilizando la prueba de Bonferroni ¿dónde se encuentran las diferencias significativas?
d. Para la semana 6, utilizando la prueba de Fisher ¿es posible encontrar dónde están las diferencias significativas?
e. Para la semana 7, utilizando la prueba de Fisher ¿es posible encontrar dónde están las  diferencias significativas?
f. Para la semana 6, utilizando la prueba de Tukey ¿es posible encontrar dónde están las diferencias significativas?
g. Para la semana 7, utilizando la prueba de Tukey ¿es posible encontrar dónde están las diferencias significativas?
h. Para la semana 6, utilizando la prueba de Bonferroni ¿es posible encontrar dónde están las diferencias significativas?
i. Para la semana 7, utilizando la prueba de Bonferroni ¿es posible encontrar dónde están las diferencias significativas?
j. Utilizando la prueba de Tukey, determine dónde se encuentran las diferencias significativas desde la semana 1 hasta la semana 8. Presente estos resultados en una tabla adecuada.

::: {#exr-doe5}
El proyecto de Mark Norman y Daniel Kasawa tenía como objetivo desarrollar un producto herbicida preemergente con la doble funcionalidad del biochar y la pendimetalina. El producto se administró en forma de pellets y en polvo para evaluar su eficacia relativa, la eficacia en el control de las malezas y su impacto en el crecimiento del maíz. El experimento abarcó seis tratamientos distintos distribuidos aleatoriamente en varias parcelas, cada uno de ellos sometido a cuatro repeticiones. El estudio incorporó dos bloques: uno con aplicación previa de biochar (A) y otro desprovisto de cualquier tratamiento con biochar (B). Los tratamientos usados fueron:

- **T1**: NPK (10-30-10)
- **T2**: NPK (10-30-10) + Pendimetalina
- **T3**: Biochar (pellet) + NPK (10-30-10) + Pendimetalina (incorporada en el biochar)
- **T4**: Biochar (polvo) + NPK (10-30-10) + Pendimetalina (incorporada en el biochar)
- **T5**: Biochar (pellet) + NPK (10-30-10) + Pendimetalina (rociada en el suelo)
- **T6**: Biochar (polvo) + NPK (10-30-10) + Pendimetalina (rociada en el suelo)

En la hoja _biomass_ del archivo _data_MN_DK.xlsx_ se encuentran los datos a ser analizados en este ejercicio, adicionalmente en la hoja _dict_biomass_ se incluyen las etiquetas para las variables _Leaves_, _Height_ y _Diameter_. Las variables presentes en la hoja _biomass_ son:

- **Date**: fecha de la medición.
- **Measurement**: número de medición.
- **Treatment**: tratamiento.
- **Block**: bloque en el que se realizó la medición.
- **Repetition**: repetición. Para cada repetición se tomaron 3 mediciones.
- **Leaves**: número de hojas. 
- **Height**: altura de la planta en centímetros.
- **Diameter**: diámetro de la planta en milímetros.
:::

a. Cree un proyecto llamado *Pg_MN_DK*.
b. Cargue los datos de las hojas _biomass_ y _dict_biomass_.
c. Para cada repetición se tomaron 3 mediciones, es decir que se debe calcular el promedio de las 3 mediciones para tener el valor de cada repetición. Utilizando la función `summarise_at`, calcule la media de las 3 mediciones para cada repetición. 
d. Daniel y Mark tuvieron problemas con los datos del tratamiento 3, repetición 2, bloque B por lo que decidieron eliminar estos datos del análisis. Filtre los datos para poder realizar esta tarea. 
e. La variable **Measurement** no está relacionada con las fechas en que se tomaron los datos. Crear una variable llamada **Measurement** a partir de la variable **Date**.
f. Utilizando la función `pivot_longer`, transforme los datos de formato ancho a formato largo. Las columnas que deben ser transformadas son **Leaves**, **Height** y **Diameter**. Los nombres de las variables deben ser guardados en una variable llamada **Variable** y los valores en una variable llamada **Value**. Adicionalmente crear una variable llamada **Week** que sea igual al doble del número de medición.
g. Crear las siguientes tablas:
  - `stats_all_long_trt_bl`: estadísticas agrupando por medición, semana, tratamiento, bloque y variable.
  - `stats_all_long_bl`: estadísticas agrupando por medición, semana, bloque y variable.
  - `stats_all_long_trt`: estadísticas agrupando por medición, semana, tratamiento y variable.

Todas las tablas deben contener: 

  - La media y la desviación de la altura.
  - El valor crítico de la distribución $t$  para el número de observaciones calculado con un $95\%$ de confianza.
  - El error estándar de la media de la  altura.
  - Los extremos del intervalo del $95\%$ de confianza  para la media de la altura.
h. Realice la prueba ANOVA para cada medición para verificar si existen diferencias significativas por tratamiento, tomando en cuenta el bloque. Posteriormente realice la prueba de Bonferroni para verificar donde se encuentran las diferencias significativas. En un objeto llamado `groups_trt` almacene los grupos resultantes de realizar la prueba de Bonferroni por tratamiento y en un objeto llamado `groups_block` almacene los grupos resultantes de realizar la prueba de Bonferroni por bloque. Con ayuda de la función `left_join` una estos dos objetos con las tablas `stats_all_long_trt` y `stats_all_long_bl` respectivamente.
i. Con la función `dir.create` crear una subcarpeta llamada **biomass** dentro de la carpeta **graficos**. Dentro de esta carpeta, guarde para cada variable dentro de cada bloque un gráfico de líneas y un diagrama de cajas. En la carpeta **biomass** deben existir 12 gráficos. 
j. Con la función `dir.create` crear una subcarpeta llamada **blocks** dentro de la carpeta **biomass** creada en el literal anterior. Dentro de esta carpeta, guarde para cada variable separados bloque un gráfico de líneas y un diagrama de cajas. En la carpeta **blocks** deben existir 6 gráficos. 
k. A partir de la tabla `stats_all_long_bl`, generar una tabla como la @tbl-mod1dkmn y guardarla en `stats_all_long_bl2`, esta última tabla debe tener 12 filas y 4 columnas. A partir de la tabla  `stats_all_long_trt` generar una tabla como la @tbl-mod2dkmn y guardarla en `stats_all_long_trt2`, esta última tabla debe tener 12 filas y 8 columnas.
j. Guardar las dos tablas del literal anterior en un archivo llamado **stats_biomass.xlsx**, en hojas llamadas **Blocks** y **Treatments** respectivamente.

| Week     | Variable | A                                                          | B                                                          |
|----------|----------|------------------------------------------------------------|------------------------------------------------------------|
| 2        | Diameter | $\mu_{W2-DA} \pm \sigma_{W2-DA}$ grupo | $\mu_{W2-DB} \pm \sigma_{w2-DB}$ grupo |
| 2        | Height   | $\mu_{W2-HA} \pm \sigma_{W2-HA}$ grupo     | $\mu_{W2-HB} \pm \sigma_{W2-HB}$ grupo     |
| $\vdots$ | $\vdots$ | $\vdots$                                                   | $\vdots$                                                   |
| 8        | Diameter | $\mu_{W8-DA} \pm \sigma_{W8-DA}$ grupo | $\mu_{W8-DB} \pm \sigma_{W8-DB}$ grupo |
| 8        | Height   | $\mu_{W8-HA} \pm \sigma_{W8-HA}$ grupo     | $\mu_{W8-HB} \pm \sigma_{W8-HB}$ grupo     |

: Tabla modelo 1 {#tbl-mod1dkmn}

| Week     | Variable | T1                                                           | $\ldots$ | T6                                                           |
|----------|----------|--------------------------------------------------------------|----------|--------------------------------------------------------------|
| 2        | Diameter | $\mu_{W2-DT1} \pm \sigma_{W2-DT1}$ grupo | $\ldots$ | $\mu_{W2-DT6} \pm \sigma_{W2-DT6}$ grupo |
| 2        | Height   | $\mu_{W2-HT1} \pm \sigma_{W2-HT1}$ grupo     | $\ldots$ | $\mu_{W2-HT6} \pm \sigma_{W2-HT6}$ grupo     |
| 2        | Leaves   | $\mu_{W2-LT1} \pm \sigma_{W2-LT1}$ grupo     | $\ldots$ | $\mu_{W2-LT6} \pm \sigma_{W2-LT6}$ grupo     |
| $\vdots$ | $\vdots$ | $\vdots$                                                     | $\vdots$ | $\vdots$                                                     |
| 8        | Diameter | $\mu_{W8-DT1} \pm \sigma_{W8-DT1}$ grupo | $\ldots$ | $\mu_{W8-DT6} \pm \sigma_{W8-DT6}$ grupo |
| 8        | Height   | $\mu_{W8-HT1} \pm \sigma_{W8-HT1}$ grupo     | $\ldots$ | $\mu_{W8-HT6} \pm \sigma_{W8-HT6}$ grupo     |
| 8        | Leaves   | $\mu_{W8-LT1} \pm \sigma_{W8-LT1}$ grupo     | $\ldots$ | $\mu_{W8-LT6} \pm \sigma_{W8-LT6}$ grupo     |

: Tabla modelo 2 {#tbl-mod2dkmn}


::: {#exr-doe6}
La investigación de Adnise Samanta Christophe y Meriche Nayeder Toussaint, evaluó el valor nutricional de la fruta pan (Artocarpus altilis) y sus componentes (exocarpio, mesocarpio y endocarpio) en dos etapas de maduración para su uso en la alimentación de rumiantes. Se analizaron 45 frutas, destacando que el exocarpio. 
Los parámetros nutricionales fueron analizados mediante un diseño factorial $4 \times 2$, El primer factor fue la parte o componente de la planta, cuyos niveles fueron exocarpio, mesocarpio, endocarpio y fruta entera. El segundo factor fue el grado de madurez de la planta, cuyos niveles fueron inmadura y madura.
En la hoja _nutriconal_ del archivo _nutricional_24017.xlsx_ se encuentran los datos analizados por Meriche y Adnise. Las variables presentes en el conjunto de datos son:

- Madurez: grado de madurez de la planta.
- Componente: parte de la planta.
- Repetición: número de repetición.
- MS: porcentaje de materia seca.
- PC: porcentaje de proteína cruda.
- FDN: fibra detergente neutra (%)
- FDA: fibra detergente ácida (%)
- MM: materia mineral (%)
- MO: materia orgánica (%)
- CHOs: carbohidratos totales (%)
:::
Se pide, analizar el efecto del grado de madurez y del componente junto con la interacción entre la madurez y el componente sobre las variables respuesta. 