project:
  type: book

lang: es 
language: es.yml

book:
  title: "Análisis de Datos en Agricultura con R y RStudio"
  author: "Prof. Oswaldo Navarrete Carreño"
  chapters:
    - index.qmd
    - intro.qmd
    - 01-concepts.qmd
    - 02-estdesc.qmd
    - 03-distr.qmd
    - 04-sampling.qmd
    - 05-icph.qmd
    - 06-regresion.qmd
    - 07-DOE.qmd
    - references.qmd


bibliography: references.bib
csl: apanoa.csl



format:
  live-html:
    theme: earth.scss
    toc-expand: false
    toc-depth: 4
    anchor-sections: true
    math: mathjax
    css: include/webex.css
    include-after-body: include/webex.js
    google-analytics: G-MSKC07TCWB
    
  
engine: knitr

editor: source


